#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

file=/etc/nginx/sites-enabled/default
sed -i 's/8080 default/80 default/' $file
sudo service nginx restart
